AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  SQSQueue1:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQSQueue1
      SqsManagedSseEnabled: true
    Metadata:
      SamResourceId: SQSQueue1
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
    Metadata:
      SamResourceId: Table
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          SQSQUEUE1_QUEUE_NAME: !GetAtt SQSQueue1.QueueName
          SQSQUEUE1_QUEUE_ARN: !GetAtt SQSQueue1.Arn
          SQSQUEUE1_QUEUE_URL: !Ref SQSQueue1
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Function1
      CodeUri: Function1/
      Handler: app.lambda_handler
      Runtime: python3.14
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        ServerlessRestApiGEThello:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SQSQueue1.QueueName
    Metadata:
      SamResourceId: Function1
  Function1LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Function1}
    Metadata:
      SamResourceId: Function1LogGroup
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Function2/
      Description: HelloWorld Lambda function
      MemorySize: 128
      Timeout: 3
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          LAMBDAIACTABLE_TABLE_ARN: arn:aws:dynamodb:eu-west-2:348345791015:table/sam-app-LambdaIaCTable-1CRCC2OZZYQEA
          LAMBDAIACTABLE_TABLE_NAME: sam-app-LambdaIaCTable-1CRCC2OZZYQEA
          TABLE_TABLE_NAME: !Ref Table
          TABLE_TABLE_ARN: !GetAtt Table.Arn
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
        DestinationConfig: {}
      PackageType: Zip
      Policies:
        - Statement:
            - Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
              Effect: Allow
            - Action:
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:PutItem
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:UpdateItem
                - dynamodb:BatchWriteItem
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
                - dynamodb:ConditionCheckItem
              Resource:
                - arn:aws:dynamodb:eu-west-2:348345791015:table/sam-app-LambdaIaCTable-1CRCC2OZZYQEA
                - arn:aws:dynamodb:eu-west-2:348345791015:table/sam-app-LambdaIaCTable-1CRCC2OZZYQEA/index/*
              Effect: Allow
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSQueue1.Arn
            BatchSize: 1
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
    Metadata:
      SamResourceId: Function2
  Function2LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Function2}
    Metadata:
      SamResourceId: Function2LogGroup